增加设置界面
YuzhenQin/GeometryCalculator pull request #3
Opened 2024-02-25 05:39 UTC by ElectroUnity

可选择应用主题与主题色
（本人去学校前匆忙提交，因为从官方案例修改，有些文件可能有多余内容，请见谅）

2024-03-01 10:18 UTC, YuzhenQin requested changes

2024-03-01 10:18 UTC, YuzhenQin commented on interfaces/__init__.py
> +# import style_sheet
考虑删一下注释，因为从包里导入和相对导入之间应该空一行。

2024-03-01 10:18 UTC, YuzhenQin commented on interfaces/setting_interface.py
> +        # )
注释的太多了，不需要的删一下。

2024-03-01 10:18 UTC, YuzhenQin commented on interfaces/style_sheet.py
> +        return f":/gallery/qss/{theme.value.lower()}/{self.value}.qss"
请解释此文件的意义。

2024-03-01 10:18 UTC, YuzhenQin commented on interfaces/test.py
> +print(here)
请解释此文件的意义。

2024-03-03 08:27 UTC, YuzhenQin requested changes
请注意：

- Interface 的 `.py` 文件应该由 `.ui` 文件使用 `pyuic6` 生成。
- Use `interface_settings` instead of `setting_interface`.
- ^ Shu Ru Fa Huai Le.

2024-03-03 08:27 UTC, YuzhenQin commented on main.py
> +    # setTheme(theme=Theme.AUTO)
请问这里为什么注释掉了？

2024-03-05 06:12 UTC, ElectroUnity commented on main.py
> +    # setTheme(theme=Theme.AUTO)
因为有了设置界面这行代码不需要了
还有我的setting_interface.py是直接写的，没用ui文件，文件名改成interface_settings.py无所谓
（现在是在信息课上回复的，没法加ui文件）

2024-03-05 14:14 UTC, YuzhenQin requested changes

2024-03-05 14:14 UTC, YuzhenQin commented on app/config/config.json
> +        "Download": "D:/Elect/Documents/PyQt/Git/GeometryCalculator/app/download",
此文件是否应该包含在代码仓库中？考虑添加到 `.gitignore`。

2024-03-05 14:14 UTC, YuzhenQin commented on interfaces/interface_settings.py
> +# coding:utf-8
File `interface_*.py` **SHOULD** be generated from `interface_*.ui`.

**SHOULD**   This word, or the adjective "RECOMMENDED", mean that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course.

2024-06-17 08:31 UTC, YuzhenQin approved these changes

2025-07-22 08:05 UTC, zhdbk3 commented
本仓库已停止维护，请查看新仓库：[几何计算器 2](https://github.com/zhdbk3/GeometryCalculator)

（最后给你 merge 了吧，反正都一样的）

2025-07-22 08:05 UTC, merged